image: ubuntu:latest

stages:
  - build
  - deploy 

variables:
  DOCKER_HOST: tcp://docker.ciya:2375

build-packages:
  stage: build
  script:
    - apt update
    - apt install git jq -y
    - chmod +x package.sh
    - ./package.sh
  artifacts:
    paths:
      - artifacts/*

