image: ubuntu:latest

stages:
  - build
  - deploy 

variables:
  DOCKER_HOST: tcp://docker.ciya:2375

build-packages:
  stage: build
  script:
    - apk update
    - apk add git
    - ls -altrh
    - find / -name package.sh
    - chmod +x package.sh
    - ls ./package.sh
    - ./package.sh

