image: docker:19.03.13

variables:
  DOCKER_TLS_CERTDIR: "/certs"

prepare-packages:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.wolfen.za.net
    - apk update
    - apk add git
    - ./package.sh
    
